### ISSUE TITLE
Inconsistencies of LocalDateRange

### ISSUE THREAD

**Issue by perceptron8** [ThreeTen/threeten-extra#100]
I guess that the main reason for blurring distinction between [\*,&nbsp;`LocalDate.MAX`) and [\*,&nbsp;+∞) was (1) inability to construct ranges containing `LocalDate.MAX` (that's my impression after following #53 discussion). The other reason I see is (2) presence of `LocalDateRange.ofClosed` which is the only possible way to (at least try to) create [*,&nbsp;`LocalDate.MAX`].

Although fix for #53, more or less, resolved problem with (1), it introduced new problems instead. I'll try to show this later.

As a side note... One may think that using [a, b] instead of [a, b) could be a good solution for (1) and (2) - although not being so convenient to implement, but that's another story. [a, b] would indeed solve (1) and (2), but at the same time it would introduce almost the same problem with `toString`. How would you stringify [`LocalDate.MIN`,&nbsp;`LocalDate.MAX`]? Would you consider `"-999999999-01-01/+1000000000-01-01"` legal despite `"+1000000000-01-01"` being out of domain? On the other hand, using `"-999999999-01-01/+999999999-12-31"` would make [`LocalDate.MIN`,&nbsp;`LocalDate.MAX`] indistinguishable from [`LocalDate.MIN`,&nbsp;`LocalDate.MAX`). This seems like some kind of vicious circle. Finally, with [a, b] you couldn't represent empty ranges.

To summarize: with [a, b) and no `LocalDateRange.ofClosed`, there would be just one problem: (1) inability to construct ranges containing `LocalDate.MAX`.
I believe that making `LocalDate.MIN` and `LocalDate.MAX` special, caused more problems than it solved. Some of the resulting quirks are documented, some aren't.

---

I'll try to show several things at once using one example.

```
LocalDateRange range = LocalDateRange.ofClosed(
    LocalDate.MAX.minusDays(1), LocalDate.MAX.minusDays(1)
);
range.isEmpty();                            // -> false (of course)
range.lengthInDays();                       // -> 1     (so far, so good)
range.contains(LocalDate.MAX.minusDays(1)); // -> true  (obviously)
range.contains(LocalDate.MAX);              // -> true  (what???)
range.isUnboundedEnd();                     // -> true  (it's getting worse...)
```

Seems like non-empty `range` of length 1 contains 2 days, all of that despite being unbounded at the end. On the surface, no `LocalDate.MAX` involved. Weird.

As you can see, (3) `isEmpty`, `contains`, `lengthInDays` and `isUnboundedStart` / `isUnboundedEnd` are inconsistent with each other.

---

Needless to say, problem with non-expressibility hasn't disappeared. There is still no way to represent [`LocalDate.MAX.minusDays(1)`, `LocalDate.MAX.minusDays(1)`]. Internally, it is indistinguishable from [`LocalDate.MAX.minusDays(1)`, +∞). Everything close to `LocalDate.MAX` becomes suspicious. This is documented, but consequences are not so obvious and can be surprising.

There are similar problems with `LocalDate.MIN` too. For instance, [`LocalDate.MIN`, `LocalDate.MIN`) is empty and unbounded at the same time.

I know it's rather unlikely to happen, but the least I can do is to leave my two cents here. Sticking to always bounded [a, b) would be perfect. It is possible to migrate in almost entirely backward compatible way.

1. No more infinities. From now on, `isUnboundedStart` and `isUnboundedEnd` are returning `false` unconditionally.
2. [\*, `LocalDate.MAX`] silently becomes [\*, `LocalDate.MAX`), just as it is now. The only change is that resulting range doesn't contain `LocalDate.MAX`.

I agree that everything what I've just described.. those are "just" edge-cases. They should't cause much trouble in real life. And maybe they won't. However, I would argue that if there have to be some quirks in the implementation - and we're stuck with (2) I believe - they should be as "local" and "constrained" as possible (for the lack of better words). It's easier to reason about code when there's only one method referring to edge case (`ofClosed`), than where there are many (`of`, `getEnd`, `getEndInclusive`, `contains`).

**Comment by perceptron8** [comment]
BTW two related javadoc catches:

1. `isEmpty()`
> https://github.com/ThreeTen/threeten-extra/blob/2a6a40666ed3cda4f4a6b07ecaffa70bd3d9311f/src/main/java/org/threeten/extra/LocalDateRange.java#L262

shouldn't it be "exclusive"?


2. `contains(LocalDate date)`
> https://github.com/ThreeTen/threeten-extra/blob/2a6a40666ed3cda4f4a6b07ecaffa70bd3d9311f/src/main/java/org/threeten/extra/LocalDateRange.java#L334

unless it is [`LocalDate.MIN`, `LocalDate.MIN`)

**Comment by jodastephen** [comment]
Feel free to comment on https://github.com/ThreeTen/threeten-extra/commit/e916dd051994fd24961c72f4df03960a9613d9c1

**Comment by perceptron8** [comment]
You can check #102 if you like.

**Comment by jodastephen** [comment]
The commits above are how I intend to resolve this. Unbounded ranges are not something I want to remove, so the commits aim to make them work more clearly with fewer edge cases.

**Comment by perceptron8** [comment]
I'm a bit disappointed, obviously, but what can I say... you're the boss. May I just ask - what's the actual reason behind keeping unbounded ranges? _"Unbounded ranges are not something I want to remove"_ - that's too little for [Discussion].

I have to admit that after your last commits the code is less buggy. And that's great. At the same time, I can't agree that there are fewer edge cases. Previously there were 3 special values (MIN, MAX - 1, MAX), now there are 4 (MIN, MIN + 1, MAX - 1, MAX).

Please check the following.

---

https://github.com/ThreeTen/threeten-extra/blob/d13e9d43bb0ce37b4f366f696ffc7b42cfcd329a/src/main/java/org/threeten/extra/LocalDateRange.java#L169
It can't be 1 day too. `LocalDateRange.of(LocalDate.MIN, Period.ofDays(1))` throws.

---

https://github.com/ThreeTen/threeten-extra/blob/d13e9d43bb0ce37b4f366f696ffc7b42cfcd329a/src/main/java/org/threeten/extra/LocalDateRange.java#L611
Breaks for current = MAX - 1 and end = MAX. `LocalDateRange.ofUnboundedEnd(LocalDate.MAX.minusDays(2)).stream().anyMatch(LocalDate.MAX::equals)` evaluates to false. At the same time `LocalDateRange.ofUnboundedEnd(LocalDate.MAX.minusDays(2)).contains(LocalDate.MAX)` returns true.

---

https://github.com/ThreeTen/threeten-extra/blob/d13e9d43bb0ce37b4f366f696ffc7b42cfcd329a/src/main/java/org/threeten/extra/LocalDateRange.java#L614
Off-by-one? It depends... When end = MAX it's ok. For all the rest it's a little too much.

---

https://github.com/ThreeTen/threeten-extra/blob/d13e9d43bb0ce37b4f366f696ffc7b42cfcd329a/src/main/java/org/threeten/extra/LocalDateRange.java#L357
Not a bug, but shouldn't all empty ranges throw here? No [x, x) has [x, x - 1] equivalent.

---

If you don't mind, I'll try to find some alternative solutions that keep unbounded ranges, but avoid complexity. I will most likely fail, but I don't wanna give up without fight.

**Comment by jodastephen** [comment]
After various bits of research I concluded that unbounded ranges are a perfectly reasonable concept in terms of dates. And that ISO-8601 may well be adding specific syntax for them. The code changes are aimed at corner cases that are unlikely to have been used, so are OK to change.

I don't want to change `getEndInclusive()` when the range is empty, even though the date ends up before the start date. Doing so would be mean to callers.

**Comment by perceptron8** [comment]
> After various bits of research I concluded that unbounded ranges are a perfectly reasonable concept in terms of dates.

Even if they are (https://github.com/schemaorg/schemaorg/issues/1365?), It's obvious that infinities should be represented by something other than `LocalDate.MIN` and `LocalDate.MAX`. Also, for truly unbounded ranges, `getStart()` and `getEnd()` would rather throw when unbounded and so on.

Of course I understand that this is beyond discussion - backward compatibility strikes again - and that you did your best to fix anything that could be fixed. Thank you for that!

> And that ISO-8601 may well be adding specific syntax for them.

True, but "../.." clearly should be parsed to something different than "-999999999-01-01/+999999999-12-31". Conversely, `toString()` of the above two should give different results, otherwise bounded and unbounded ranges become indistinguishable.

Once again, this is beyond discussion, I know.

> I don't want to change getEndInclusive() when the range is empty, even though the date ends up before the start date. Doing so would be mean to callers.

Or... just meaningful? ;) "Inclusive" may suggest that the returned value is contained within range.

It's your decision again. Let it be.

**Comment by jodastephen** [comment]
Thanks for looking, its been helpful to have the discussion. The tricky part with an API like this is where to draw the line on "being nasty". For example, it would be possible to design the API such that it returns null from getStart/getEnd, but that just results in NPE (as no-one will check for null). Alternatively, the API could be designed to throw exceptions when queried for an unbounded value, but again no-one will check the relevant method before calling the code. So, what I'm trying to do is find a way that the code will continue and just work without the caller constantly having to baby sit the object through `isUnbounded` calls.

FWIW, if ISO do publish an unbounded form, I think I'd change the string form of this class to match. That is part of what this change is preparing for.

PS, a lot of the problems result from the concept of empty. It would be possible to remove that concept altogether, but I'm told that it does get used, so I think we're stuck with it. (I'm willing to make some incompatible changes at the margins, but not much)

The only other way I can think of to deal with this is to have two classes - one that is always bounded and one that can be unbounded - like an `Optional` wrapper. That solution does at least put the potential unbounded-ness in the caller's face, but at the expense of complexity. However, I struggle to see how well such an approach would work in practice.

**Comment by perceptron8** [comment]
I can't come up with anything better than you did. Given the constraints, 2-day margins appear to be inevitable and elegant. I'm unable to find any more bugs too! ;)

As for practice... Currently in most places I'm in control, I try to use `com.google.common.collect.ContiguousSet<LocalDate>` instead of `com.google.common.collect.Range<LocalDate>`. The reason is that not only everyone blindly assumes that `Range` is bounded on both sides ("no-one will check the relevant method before calling the code" as you said), but even worse - everyone assumes that it has particular shape: mostly [a, b), sometimes [a, b]. It's clearly asking for trouble. I was looking for some replacement giving stronger guarantees just by its type - and that's how I found `LocalDateRange`. It's a pity that it is not plain [a, b), but after last changes it looks reliable enough to be used without fear.

I'm curious how `LocalDateRange` will change when ISO do publish unbounded form. I hope I live to see this...

Again, thanks for fixes and discussion! :)

**Comment by perceptron8** [comment]
@jodastephen As you probably know, [ISO 8601-2:2019](https://www.iso.org/standard/70908.html) had been published in February 2019. Among others, it introduces extended time intervals.

> the extended interval syntax keywords 'unknown' and 'open' have been replaced with null and the double-dot notation ['..'] respectively;

See https://www.loc.gov/standards/datetime/edtf.html.

> __Open end time interval__
> Example 1          ‘1985-04-12/..’
> interval starting at 1985 April 12th with day precision; end open

> __Open start time interval__
> Example 4          ‘../1985-04-12’
> interval with open start; ending 1985 April 12th with day precision

If you would like me to change `toString`/`parse`, let me know.

**Comment by jodastephen** [comment]
I don't have a copy, given the cost. I have to say that looks like a massive increase to the spec, which would require a lot of modelling work to add here.

Should open-ended time intervals be changed? Same question for the toString of quarters. My initial feeling is not, although I'm not certain yet.
