### ISSUE TITLE
Inconsistencies of YearWeek

### ISSUE THREAD

**Issue by marcospassos** [ThreeTen/threeten-extra#103]
The class `YearWeek` supports `WEEK_OF_WEEK_BASED_YEAR` and `WEEK_BASED_YEAR`, but this a unilateral statement as `week.isSupported(WEEK_OF_WEEK_BASED_YEAR) == WEEK_OF_WEEK_BASED_YEAR.isSupportedBy(week)` evaluates to `false`.

**Comment by jodastephen** [comment]
See https://bugs.openjdk.java.net/browse/JDK-8194747 . Despite what the Javadoc says, you have to call `yearWeek.isSupported()`, not `field.isSupportedBy()`.
