### ISSUE TITLE
YearQuarter.quartersUntil

### ISSUE THREAD

**Issue by mjustin** [ThreeTen/threeten-extra#107]
I've run across scenarios where it would be convenient to have `Stream<YearQuarter> quartersUntil(YearQuarter endExclusive)` methods in `YearQuarter` analogous to the [LocalDate.datesUntil](https://docs.oracle.com/javase/9/docs/api/java/time/LocalDate.html#datesUntil-java.time.LocalDate-) methods in Java 9.

On the other hand, I do notice that no other Java 9 temporal types have a `[timeUnits]Until` method, so perhaps there's a reason to leave this out (though my guess would be that it has to do with keeping the JDK API lightweight).  For instance, [YearMonth](https://docs.oracle.com/javase/9/docs/api/java/time/YearMonth.html) could reasonably have a `monthsUntil` method, but it does not.

Note that the following Java 9 code will accomplish the desired behavior, though it's a bit fiddly:

```
YearQuarter q1 = YearQuarter.of(2015, 2);
YearQuarter q2 = YearQuarter.of(2018, 3);

Stream<YearQuarter> stream = q1.atDay(1).datesUntil(q2.atDay(1), Period.ofMonths(3)).map(YearQuarter::from);
```

**Comment by mjustin** [comment]
@jodastephen — Not that I personally have need of it, but were you also planning to add `YearWeek.weeksUntil`?  You brought it up as something that would make sense to add.

**Comment by mjustin** [comment]
Granted that we do a fair deal of quarter-level logic at my organization, but I have already made use of this feature in multiple different spots in multiple different projects already.  So thanks @jodastephen and @monicagg for making this a reality.

**Comment by monicagg** [comment]
Very welcome @mjustin, so glad you already use the feature.
