### ISSUE TITLE
Parsing week 53 of year that is 52-week long results in week 1 of next year

### ISSUE THREAD

**Issue by kprzygudzki** [ThreeTen/threeten-extra#114]
So, parsing a week number 53 of a year that is only 52 weeks long results in week 1 of the next year. Example:

    YearWeek yearWeek = YearWeek.parse("2018-W53");
    yearWeek.equals(YearWeek.of(2019, 1)); //returns true

I was wondering why it is so. I've read the code, so I do realize this behaviour is by design.

I was wondering, though, what were the motivations behind that decision. Is it related to any official ISO8601 guidelines?

**Comment by raupachz** [comment]
Agreed. The current implementation is faulty. This should throw an `java.time.DateTimeException`.

**Comment by jodastephen** [comment]
Parsing is a good case of [Postel's law](https://en.wikipedia.org/wiki/Robustness_principle). (I won't be changing the behaviour).

**Comment by kprzygudzki** [comment]
Cool, thanks for the clarification.

**Comment by raupachz** [comment]
@jodastephen Fair point, but `LocalDate.of(2018, Month.FEBRUARY, 30)` does throw an exception because the date does not exist. Neither does the week 53 in the year 2018. I think this is a valid defect.
