### ISSUE TITLE
Getting an Interval corresponding to a given YearWeek

### ISSUE THREAD

**Issue by uldall** [ThreeTen/threeten-extra#135]
We have a use case where we are storing a year plus a week in our database and want to fetch data generated in this period. To do this we are trying to get the [Interval](https://www.threeten.org/threeten-extra/apidocs/org.threeten.extra/org/threeten/extra/Interval.html) that corresponds to the given [YearWeek](https://www.threeten.org/threeten-extra/apidocs/org.threeten.extra/org/threeten/extra/YearWeek.html).

How can we get an Interval given a YearWeek (Plus a timezone)?

**Comment by Clockwork-Muse** [comment]
Uh, if you're storing a `YearWeek`, and have one as input, why aren't you _querying_ with a `YearWeek`?

Otherwise, getting the interval looks something like this:
```
Instant startInstant = inputYearWeek.atDay(DayOfWeek.Monday).atStartOfDay(inputTimeZone).toInstant();
// end of interval is start of next week.
Instant endInstant = inputYearWeek.plusWeeks(1).atDay(DayOfWeek.Monday).atStartOfDay(inputTimeZone).toInstant();
Interval queryInterval = Interval.of(startInstant, endInstant);
```
...although you had better make sure that the time zone being used is the same as was used to store the year week...

**Comment by uldall** [comment]
This will work for locales where Monday is the first day of the week. I guess I hoped there was a generalized solution.

**Comment by Clockwork-Muse** [comment]
.... you can get the "first day of week" for a given locale pretty easily:
```
Locale locale = new Locale("en", "US");
DayOfWeek dow = WeekFields.of(locale).getFirstDayOfWeek();
```

([source](https://stackoverflow.com/questions/52365194/how-to-get-the-first-day-of-week-for-a-certain-locale-country))

.... _however_, my comment about timezone **also** applies for the day-of-week.  If you've stored something based on a particular day-of-week, you must also query it based on that same day-of-week, or your results will be wrong/nonsensical.
