### ISSUE TITLE
Add Hours/Weeks classes similar to joda-time

### ISSUE THREAD

**Issue by vardlokkur** [ThreeTen/threeten-extra#14]
Would it be possible to add Hours/Weeks classes similar to joda-time? or we should simply use Duration/Period instead?

**Comment by raupachz** [comment]
The classes would be well suited for us too. I am willing to spend some time on it.

**Comment by jodastephen** [comment]
`Weeks` has been added. I'm happy to accept a PR for `Hours` and `Minutes` cut and pasted from the current ThreeTen-Extra classes and tests.

**Comment by raupachz** [comment]
I created a pull request for `Hours` and `Minutes` classes.
