### ISSUE TITLE
threeten.org's link to the license is broken

### ISSUE THREAD

**Issue by cpovirk** [ThreeTen/threeten-extra#145]
> ThreeTen-Extra is licensed under the business-friendly [BSD 3-clause license](https://www.threeten.org/threeten-extra/license.html).

(https://www.threeten.org/threeten-extra/)

That leads to https://www.threeten.org/threeten-extra/license.html, which is a 404.

I'm not sure if the best place to link is https://github.com/ThreeTen/threeten-extra/blob/master/LICENSE.txt or elsewhere.

**Comment by jodastephen** [comment]
Fixed thanks
