### ISSUE TITLE
Add isPositive(), isZero(), and isNegative() to the additional TemporalAmounts

### ISSUE THREAD

**Issue by kluever** [ThreeTen/threeten-extra#148]
Just as `Duration` and `Period` have, it would be useful to have `isZero()` and `isNegative()` instance methods on the additional `TemporalAmount` types that ThreeTenExtra provides (e.g., `Days`).

**Comment by jodastephen** [comment]
If you want to raise a PR for `isZero()`, `isPositive()` and `isNegative()`, feel free. I'd suggest starting with one class, getting that agreed, and then rolling it out to the other amounts.

**Comment by kluever** [comment]
FWIW, the `TemporalAmount`s in `java.time` don't have `isPositive()`, so if we want to be consistent, we'd only add `isZero()` and `isNegative()`.

**Comment by jodastephen** [comment]
`Period` doesn't have `isPositive()` because it is multi-field. `Duration` probably should in the JDK. So yes I think we should add `isPositive()` here.

**Comment by kluever** [comment]
Re. `Duration.isPositive()`, see [JDK-8171382](https://bugs.openjdk.java.net/browse/JDK-8171382)
