### ISSUE TITLE
Interval#hashCode has a bug?

### ISSUE THREAD

**Issue by skingsland** [ThreeTen/threeten-extra#160]
I'm using `org.threeten.extra.Interval` in a DTO class, and when I test that class's equals() and hashCode() implementations with [nl.jqno.equalsverifier.EqualsVerifier](https://jqno.nl/equalsverifier/), it fails with this error message:
```
Significant fields: equals relies on comparisonInterval, but hashCode does not.
  MyClass[myInterval=-1000000000-01-01T00:00:00Z/-1000000000-01-01T00:00:00Z, ...other fields...] has hashCode 805711495
  MyClass[myInterval=+1000000000-12-31T23:59:59.999999999Z/+1000000000-12-31T23:59:59.999999999Z, ...other fields...] has hashCode 805711495
```

So I wrote an equals/hashCode test for `Interval`, using the same Instant values that `EqualsVerifier` used above:
```
  @Test
  public void testIntervalEquals() {
    // this passes
    EqualsVerifier.forClass(Interval.class).withNonnullFields("start", "end").verify();

    Interval interval1 = Interval.parse("-1000000000-01-01T00:00:00Z/-1000000000-01-01T00:00:00Z");
    Interval interval2 = Interval.parse("+1000000000-12-31T23:59:59.999999999Z/+1000000000-12-31T23:59:59.999999999Z");
    assertNotEquals(interval1, interval2);

    // this fails:
    assertNotEquals(interval1.hashCode(), interval2.hashCode());
  }
```
The test fails because the intervals are _not_ equal, but the hash codes are. Is there a bug in [Interval#hashCode](https://github.com/ThreeTen/threeten-extra/blob/master/src/main/java/org/threeten/extra/Interval.java#L583), or is there something wrong with my test?

**Comment by perceptron8** [comment]
See https://docs.oracle.com/javase/8/docs/api/java/lang/Object.html#hashCode--.

> It is _not_ required that if two objects are unequal according to the `equals(java.lang.Object)` method, then calling the `hashCode` method on each of the two objects must produce distinct integer results. However, the programmer should be aware that producing distinct integer results for unequal objects may improve the performance of hash tables.

**Comment by perceptron8** [comment]
It seems to be a known false positive: https://github.com/jqno/equalsverifier/issues/259.

**Comment by perceptron8** [comment]
You can find a workaround here: https://jqno.nl/equalsverifier/errormessages/significant-fields-equals-relies-on-foo-but-hashcode-does-not/.

**Comment by skingsland** [comment]
Holy cow this is _exactly_ the issue I'm describing:

> One special case is when EqualsVerifier generates instances for the class’s fields that happen to have the same hashCodes. For instance, the Interval class from ThreeTen-extra implements hashCode() like this:
>
> 
```
@Override
public int hashCode() {
    return start.hashCode() ^ end.hashCode();
}
```
> EqualsVerifier selects the same values for start and end, causing the hashCode() method to return equal values for both instances.

**Comment by skingsland** [comment]
OK never mind then, I will close this issue because it's clearly not a problem for this library.

**Comment by Clockwork-Muse** [comment]
@skingsland - note that the reason unequal objects might have equal hashcodes (ignoring the specifics of what's happening here) has to do with how many different values are possible.
 - an `int` hash code has 2^32 different values.
 - An `Interval` has ~2^188 possible values:
    - Two `Instant`s, with ~2^94 possible values:
      - A `long`, with 2^64 different values
      - A constrained `int`, with ~2^30 possible values

... that is, for well-distributed hashing, there's ~2^156 different `Interval`s (assuming I've done my math correctly) that hash to the same value...
