### ISSUE TITLE
SemVer support

### ISSUE THREAD

**Issue by dagguh** [ThreeTen/threeten-extra#164]
Can this lib support [Semantic Versioning](https://semver.org/spec/v2.0.0.html)?
If so, what is the public API?

**Comment by raupachz** [comment]
Release 1.5.0 is the current release. Could you elaborate more what you are trying to achieve?

**Comment by dagguh** [comment]
For example, I'm using `org.threeten.extra.MutableClock`. It was added in 1.3.
Can I bump to 1.4 without fear of broken compilation or `NoSuchMethodError` in runtime? Can I do the same with 1.5 or future 1.6, 1.7, etc?

If [SemVer](https://semver.org/spec/v2.0.0.html) is declared and the [public API](https://semver.org/spec/v2.0.0.html#spec-item-1) includes [source compatibility](http://cr.openjdk.java.net/~darcy/OpenJdkDevGuide/OpenJdkDevelopersGuide.v0.777.html#source_compatibility) + [binary compatibility](http://cr.openjdk.java.net/~darcy/OpenJdkDevGuide/OpenJdkDevelopersGuide.v0.777.html#binary_compatibility) of the `MutableClock` class, then I can rest assured that bumps are safe.

**Comment by jodastephen** [comment]
ThreeTen-Extra is maintained like Joda-Time, which has an excellent record of compatibility between point releases. Note "This release is considered stable and worthy of the 1.x tag."

**Comment by dagguh** [comment]
That's good to hear.
So perhaps I could assume partial de facto SemVer. I'd depend on the `[1.3, 2.0)` range with more confidence.

Would you consider supporting SemVer to make the compatibility promises explicit? Other consumers could quickly gain the same confidence without having to ask.

**Comment by dagguh** [comment]
Awesome! ♥️
