### ISSUE TITLE
Add Duration parsing support to match Abseil C++ and Golang

### ISSUE THREAD

**Issue by TristonianJones** [ThreeTen/threeten-extra#180]
Golang's `time.ParseDuration` routine parses a very human-readable string format for duration values. This functionality was ported into the Abseil C++ library which makes it easy to consume the same duration strings in both C++ and Golang. Java does have support for duration parsing to a `java.time.Duration`, but not in the same format. If the same routines were ported to a common library, then the same format could be used easily across all three languages.

Proposed API change:

```java
package org.threeten.extra;

import java.time.Duration;

public final class Temporals {
  /**
   * Parses input {@code text} into a {@code java.time.Duration} using the duration format string
   * implemented in Golang's {@code time.ParseDuration} and Abseil C++ {@code time::ParseDuration}
   */ 
  public static  Duration parseDuration(CharSequence text) {
    ...
  }
}
```

For reference:
https://github.com/abseil/abseil-cpp/blob/9fde5a6eb081ea080f5aa895102a9154c3a2d09f/absl/time/time.h#L548
https://golang.org/pkg/time/#ParseDuration

I have an implementation of this functionality, and would be willing to contribute it. Please let me know what API definition you'd like and I'll happily accommodate the change. My hope would be, as much as possible, to provide a clear connection between the Golang and C++ APIs, but I understand this is not always possible or desirable.

I filed the same request on [Guava](https://github.com/google/guava/issues/5456), but there was some thought that ThreeTen would be a better home.

**Comment by jodastephen** [comment]
I'm happy to see this added.

I think it should go on `AmountFormats`, where other parse methods can also be added over time. The format-style needs a name though, like the existing "wordBased". maybe "unitBased". 

* `unitBased(Duration)` - formats the duration
* `parseUnitBasedDuration(CharSequence)` - parses

There may be a case for adding an `AmountFormatter` interface or abstract class to allow users to choose and pass around their format, but that can be a separate change.

**Comment by TristonianJones** [comment]
Excellent! In that case, I'll start a pull request next week and we can refine the API during the review, using `parseUnitBasedDuration` as a starting point.
