### ISSUE TITLE
Year Half

### ISSUE THREAD

**Issue by dansiviter** [ThreeTen/threeten-extra#200]
Support concept of Year Half. This is useful for some industries, such as finance, to represent the beginning or trailing ends of a year.

AFAIK there is no standard representation, but typically `<year>-H<1|2>` (e.g. `2022-H2`) is used and similar to Year Quarter.

**Comment by jodastephen** [comment]
This would be a good addition to ThreeTen-Extra, modelled as per quarters.

**Comment by jodastephen** [comment]
Please test and review :-)
