### ISSUE TITLE
Request: Method(s) for Mutable Clock to Set Time/Date in Time Zone of Clock

### ISSUE THREAD

**Issue by EarthCitizen** [ThreeTen/threeten-extra#368]
It would be great if `MutableClock` had methods for setting time and date in the local time zone of the clock:

`set(LocalTime localTime)`
`set(LocalDate localDate)`
`set(LocalDateTime localDateTime)`

When you need to work with times and dates in the zone of the clock, and that zone is not UTC, it is a multi-step process to make the correct time and/or date then convert that back to an `Instant` then set the value on the clock.

This could be eliminated with the suggested methods above.

**Comment by jodastephen** [comment]
True. PR welcome

**Comment by EarthCitizen** [comment]
When I submitted this, I didn't realize that this method already allows that:

`public void set(TemporalAdjuster adjuster)`

Closing this at it is already possible.
