### ISSUE TITLE
Duration.multipliedBy(double)

### ISSUE THREAD

**Issue by cowwoc** [ThreeTen/threeten-extra#40]
I am attempting to reimplement https://developers.google.com/api-client-library/java/google-http-java-client/reference/1.20.0/com/google/api/client/util/ExponentialBackOff in terms of Durations. At some point, I need to multiply a Duration by a double multiplier.

Is there a reason `Duration.multipliedBy()` only takes an integer? Or can a double variant be added?

**Comment by jodastephen** [comment]
A double variant would need to have some kind of rounding support. It is certainly a more complex operation as such. I don't believe that Oracle would support the addition to the JDK.

**Comment by kluever** [comment]
FWIW, at Google, we have a lot of legacy APIs that unfortunately represent deadlines as a double of seconds, and thus we have a handful of similar APIs:

`Durations.ofSeconds(double)`
`Durations.toSecondsAsDouble(Duration)`

...and a feature request for `Durations.multiply(Duration, double)`

**Comment by jodastephen** [comment]
What do you think it should do wrt rounding?

**Comment by kevinb9n** [comment]
From the peanut gallery: i think this is a case where user control over rounding is very rarely needed. I would suggest it always round up to the next nano (to avoid very small values becoming the magic value zero, which sometimes gets treated as "infinite" by bad APIs).

**Comment by jodastephen** [comment]
Any thoughts? https://github.com/ThreeTen/threeten-extra/pull/147

**Comment by perceptron8** [comment]
@cowwoc #147 has been merged, so it looks that this issue may be closed.

**Comment by cowwoc** [comment]
Looks good to me.
