### ISSUE TITLE
PeriodFormatter

### ISSUE THREAD

**Issue by cowwoc** [ThreeTen/threeten-extra#41]
http://blog.joda.org/2014/11/converting-from-joda-time-to-javatime.html says that PeriodFormatter is not included in java.time. Can this be added to threeten-extra?

**Comment by jodastephen** [comment]
Some kind of period formatter would be a good addition.

**Comment by raupachz** [comment]
How would one work with the separation of Period and Duration in java.time? In Joda-Time there is only Period that covers date and time based access. In Joda-Time you can create a PeriodFormatterthat prints and parses something like `2 days 10 hours 4 minutes 0 seconds`. In java.time that would work for Duration but not for Period.

**Comment by jodastephen** [comment]
See `TemporalAmount` interface.

**Comment by raupachz** [comment]
I fail to see how `TemporalAmount` helps. I try to give a better explanation of my line of thought.

Lets say I have a `Duration.of(125)`. Formatting should allow something like `0 days 2 hours 5 minutes`, but also something like `125 minutes`. This is my first problem. I would not know how to design a pattern/builder that works for both cases. `P2H5M`?

`TemporalAmount` gives field based access. Duration supports `SECONDS` and `NANOS`. Period supports `YEARS`, `MONTHS` and `DAYS`. The former stores the whole timespan in the seconds and I would have to compute either days, months from the seconds field. The latter has different fields for years, months and days. I would need to use instanceof and check if I am working with Period or Duration.

**Comment by jodastephen** [comment]
It is not possible to compute months or years from seconds. Computing days makes the assumption that the days are all 24 hours long. Thus `Duration` operates differently to `Period`. Note that `Period` also has the challenge of outputting weeks.

Thus, it seems likely that any design will need to have the ability to convert days to weeks and seconds to hours/minutes. This makes the whole thing not simple. And the Joda-Time design wasn't that great either.

**Comment by raupachz** [comment]
What would you do Stephen? You are the man. Allow values derived from seconds and accept rounded, not-exact values? Have separate formatters for Duration and Period? Or a formatter that excepts `TemporalAmount` and just zero minutes, seconds if the formatter is passed a Period?

**Comment by Clockwork-Muse** [comment]
@raupachz - The first question to really ask is: "What are you doing with the output value"?  And, I suppose, "How did you get the period and duration?".  Because it makes a difference, and you usually want different formatters for different things (or even combining multiple formatters).

**Comment by raupachz** [comment]
@Clockwork-Muse Most of the time we track time in minutes. At some point you want to show the value to the user. Unfortunately we have different formats. 123 minutes could be `2 Std 3 Min`, `2:03`, this `02:03` and yes even `123 Minuten`. Ignore the locale, but yes we need an exact value.

We also have the use case of tracking days and even mixing days with hours. Unfortunately a day does not mean 24 hours but working hours which could be something like 8 hours.

Before we used joda-time we had the classical `int` and `java.util.Date` approach and various helper classes for date-time manipulation/display. Then we started to use `joda-time` and finally migrated to `java.time`. The `TemporalAmount` is nice. At the moment we use the `Minutes` class in threeten-extra instead of `Duration`.

I was just thinking of a more general approach instead of all the different formatter everywhere.

**Comment by jodastephen** [comment]
Just to answer the earlier question. I don't really know what a good API for formatting amounts would look like. The one in Joda-Time was unpleasant and complex, but it does have good I18N natural text support. Maybe the start is to port the word-based support with an a separate API that doesn't involve writing a formatter:

    AmountFormats.wordBased(Period, Locale)
    AmountFormats.wordBased(Duration, Locale)
    AmountFormats.wordBased(Period, Duration, Locale)

With ISO-8601 handled by `java.time` itself, there is less need for a complex formatter anyway. However a method to combine the formats would be useful:

    AmountFormats.iso8601(Period, Duration)

**Comment by jodastephen** [comment]
I started a branch for this, but don't have time to finish it ATM.

**Comment by jodastephen** [comment]
The next release will have basic word-based formatting. More translations welcome.
