### ISSUE TITLE
Interval.Parse and ISO 8601 time intervals

### ISSUE THREAD

**Issue by steve-o** [ThreeTen/threeten-extra#49]
It appears only `<start>/<end>` is supported whilst Wikipedia lists these:

```<start>/<end>
<start>/<duration>
<duration>/<end>
<duration>
```

And Joda Time supports:

```<start>/<end>
<start>/<duration>
<duration>/<end>
```

The most flexible addition would be `<start>/<duration>`.

**Comment by jodastephen** [comment]
Closed by #50
