### ISSUE TITLE
Support open Intervals

### ISSUE THREAD

**Issue by cheppsn** [ThreeTen/threeten-extra#53]
We have a lot of time interval queries in our system ("find data between x and y"). We'd like to formulate our queries with Interval objects.

However, sometimes we have queries with open intervals (i.e. "all data before y" or "all data after x"). Instead of creating new query methods we'd rather just pass in an open interval [*,y] or [x,*].

This is currently not possible, because creation of Interval objects does not permit to specify null boundaries.

**Comment by raupachz** [comment]
Why don't you pass `Instant.MAX` or `Instant.MIN` to the constructor of the interval? Maybe I am missing something but this way you could have your open intervals.

**Comment by jodastephen** [comment]
I agree that using `MIN` and `MAX` is the best approach. Perhaps some factory methods could be added to do this, although I'm not convinced yet.

**Comment by cheppsn** [comment]
I think this is a good suggestion for a workaround. But from a modelling perspective I'd still prefer a handling of open interval bounds, after all it is a _fact_, that one end is _not_ defined.

Although the toString()-Output of Interval with an `Instant.MAX/MIN` Value is clearly recognizable as "artificial" (`2016-01-11T11:32:07.211Z/+1000000000-12-31T23:59:59.999999999Z`), wouldn't it be nicer to e.g. see `2016-01-11T11:32:07.211Z/-` instead? When outputting tabular data with intervals it might still be hard to spot, also when debugging. Special handling might be needed when passing the inverval around, which does maybe not result in clearly readable code if it has to work with comparisons to `Interval.MAX/MIN`.

I'd certainly welcome factory methods (and maybe some test methods like `isEndOpen()` or `isStartOpen()`).

I realize that this is a somewhat purist claim that may be argued away as having purely semantic value. However I'll stop bugging about this, and leave the decision to the framework implementors.

**Comment by raupachz** [comment]
No, I totally agree your with your point. From a semantic standpoint you are right, but if you change the `Interval` logic and allow some `null` values in the constructor you don't comply with the rules of `java.time`. It does not permit `null`.

I am actually more with you than you think. In our application we have to deal with ranges of `LocalDateTime` for time tracking. We have to allow `null` for start or end. I was thinking about adding a custom class for `threenten-extra`, but I don't know how it would fit in. `Interval` is for `Instant`, so I can't really use it either. It is still custom code and legacy targeting still `java.util.Date`.

Are you working with `LocalDateTime` or `Instant`. How would you do it? How could we make it comply with the general conventions of `java.time`? Maybe we can figure something out together.

**Comment by jodastephen** [comment]
I've added boolean query methods and beefed up the docs regarding MIN/MAX. The toString format is ISO-8601, so changing that has other implications. I think the current design is where the code should stay in design terms.
