### ISSUE TITLE
Release 0.10?

### ISSUE THREAD

**Issue by raupachz** [ThreeTen/threeten-extra#54]
Hi Stephen,

any chances we see a 0.10 release soon? Really looking forward to add threeten-extra as a "real" maven dependency.

**Comment by raupachz** [comment]
Any updates?

**Comment by jodastephen** [comment]
Life (baby #2) currently intervening.

**Comment by raupachz** [comment]
Congratulations!

**Comment by jodastephen** [comment]
Released v1.0
