### ISSUE TITLE
Support to try to parse String using multiple patterns

### ISSUE THREAD

**Issue by cgendreau** [ThreeTen/threeten-extra#56]
Not sure what would be the best way to achieve that but I think it would be useful to be possible to test different patterns to parse a String that represents a date/datetime in an unknown format.

I tried the following with no success:

``` java
DateTimeFormatterBuilder builder = new DateTimeFormatterBuilder();
//simplified for readability
String[] patterns = {"yyyy-MM-dd","yyyy-MM-dd HH:mm:ss","yyyy-MM-dd'T'HH:mm:ss"};
for(String pattern : patterns) {
    builder.appendOptional(DateTimeFormatter.ofPattern(pattern));
}
DateTimeFormatter dtFormatter = builder.toFormatter();
TemporalAccessor ta = dtFormatter.parseBest(input, LocalDateTime.FROM, LocalDate.FROM,);
```

It seems to work if I only provide patterns that are very similar otherwise, I have a `DateTimeParseException: could not be parsed, unparsed text found at index ...`.

What I have in mind is something similar to Apache [DateUtils.parseDate()](https://commons.apache.org/proper/commons-lang/javadocs/api-release/org/apache/commons/lang3/time/DateUtils.html#parseDate%28java.lang.String,%20java.lang.String...%29).

Maybe this is out-of-scope for threetenbp so that why I am reporting it in threeten-extra.

Please let me know if my test above is wrong and/or there is more documentation about how this could be implemented.

**Comment by jodastephen** [comment]
Something to do this would be a useful addition. It could live in `Temporals`.

However, your example does not really need the full power of the proposed feature.

The pattern "yyyy-MM-dd[['T'][ ]HH:mm:ss]" would come very close to what you want. See also [this answer](http://stackoverflow.com/questions/34810324/java-8-offset-date-parsing/34811228#34811228) for how to default parts of the result.
