### ISSUE TITLE
'YearQuarter' documented as being ISO 8601, but that standard has no quarters.

### ISSUE THREAD

**Issue by basil-bourque** [ThreeTen/threeten-extra#58]
The class documentation for [`YearQuarter`](http://www.threeten.org/threeten-extra/apidocs/org/threeten/extra/YearQuarter.html) claims to be:

> A year-quarter in the ISO-8601 calendar system

But the ISO 8601 standard does not appear to have any mention of "quarter". In drafts I have seen for ISO 8601:1998 and ISO 8601:2004(E), neither PDF document contains the word "quarter" or "Q1". The [Wikipedia page](https://en.wikipedia.org/wiki/ISO_8601) for ISO 8601 makes no mention of quarters. The [text of RFC 3339](https://tools.ietf.org/html/rfc3339) (a profile of ISO 8601) makes no mention of "quarter".

More importantly, the `YearQuarter` class defines quarter by the calendar weeks/months with January 1 starting Q1, April 1 starting Q2, and so on. That, in and of itself, is fine. But, when mentioning ISO 8601, the standard’s definition of weeks springs to mind. The reader may well think that an ISO 8601 quarter might align with those standard weeks rather than calendar weeks. 

I suggest the class documentation be edited to:

- Clarify whatever was meant by the mentions of ISO 8601. (I am not clear myself)
- Explicitly define quarters as being calendar-based (January 1, April 1, July 1, October 1).

**Comment by jodastephen** [comment]
"ISO-8601 calendar system" refers to the calendar system, not the spec. The calendar system is simply a way to refer to the current *de facto* civil calendar system without using the word "Gregorian". Quarters are defined within that by `Month.firstMonthOfQuarter()`.
