### ISSUE TITLE
Symmetry010 handles ALIGNED_DAY_OF_WEEK_IN_MONTH incorrectly, claims each month starts on a monday

### ISSUE THREAD

**Issue by Clockwork-Muse** [ThreeTen/threeten-extra#61]
The Symmetry010 date and chronology [claim every month starts on a Monday](https://github.com/ThreeTen/threeten-extra/blob/master/src/main/java/org/threeten/extra/chrono/Symmetry010Chronology.java#L76):
>  <li>Week day - every month starts on a Monday.  There are no days outside of the week or month.

This is false; every _quarter_ (and year) starts on a Monday.
I haven't looked to see if anything other than the documentation would need to be adjusted.

@catull

**Comment by catull** [comment]
Well caught, this is indeed incorrect.

Since a year has either 52 or 53 (leap year) full weeks, each year starts on the same week day.
Also, since quarters are 13 or 14 (4th quarter in a leap year) full weeks, each of them starts on the same week day, too.  In each quarter, the first month starts on a Monday, the second month on a Wednesday and the 3rd on a Saturday.

The Symmetry454 calendar system goes beyond that.
Here, all months start on a Monday, because months have either 4 or 5 full weeks.

Since Symmetry454 date and chronology was implemented first, it served as a template for Symmetry010 date and chronology.  Thus the documentation bug above was missed in the process.

I correct the documentation accordingly.

**Comment by Clockwork-Muse** [comment]
Does the "aligned day of week in month" need to be adjusted as well?

**Comment by catull** [comment]
I don't think so.
Either SymmetryYXY do not have special days, weeks or months which complicate the alignment, in the way  DiscordianDate has with St. Tibbs day.
Even the leap week is not that special, it does extends December, but leaves the alignment intact.

**Comment by Clockwork-Muse** [comment]
...That's not what the alignment is talking about (special days like that are immaterial).  An aligned "day of week in month" makes it so the first day of the month is the first day of the week; weeks are thus "aligned" to the month.  Symmetry010 mucks with alignment because not every month starts on the same day of the week.

**Comment by catull** [comment]
Had to look up the meaning of "to muck with".
Basically, you have found an implementation bug.
I am working on correcting the bug, with the contradiction in the documentation being removed along the way.

**Comment by catull** [comment]
Just out of curiosity, where exactly does it say that an aligned day-of-week in a month "makes it so the first day of the month is the first day of the week" ?

The official documentation at http://docs.oracle.com/javase/8/docs/api/java/time/temporal/ChronoField.html#ALIGNED_DAY_OF_WEEK_IN_MONTH  states:

"For example, in a calendar systems with a seven day week, the **first aligned-week-of-month starts on day-of-month 1**, the second aligned-week starts on day-of-month 8, and so on. Within each of these aligned-weeks, the days are numbered from 1 to 7 and returned as the value of this field. As such, day-of-month 1 to 7 will have aligned-day-of-week values from 1 to 7. And day-of-month 8 to 14 will repeat this with aligned-day-of-week values from 1 to 7."

**Comment by Clockwork-Muse** [comment]
... it says it right there:  

> As such, day-of-month 1 to 7 will have aligned-day-of-week values from 1 to 7.

Also, check how `AbstractDate` implements the field.

**Comment by catull** [comment]
I do not agree with your interpretation.

All it states is that the first of the month starts a series from 1 to 7, dubbed aligned-day-of-week.
This series is repeated 4 or 5 times.
Which day-of-week the month starts with is secondary.

So if a month starts on a thursday, the first series of aligned-day-of-week goes from Thursday 1st of MONTH through to Wednesday 7th of MONTH, not from Monday 5th through Sunday 12th.

It does not state "As such, day-of-month 1 to 7 will have **day-of-week** values from 1 to 7."

This is different from "first full week in the month that starts on a monday", which itself can start anywhere from days-of-month 1 to 7, such as the 5th through the 12th in the case above.

AbstractDate#getAlignedDayOfWeekInMonth calculates
     ((getDayOfMonth() - 1) % lengthOfWeek()) + 1;

There is no offset with respect to the day-of-week here: it shifts the modulo 7 value one up.
So, aligned-day-of-week 1 does not imply Monday, it can be any one week day.

AbstractDate#with(TemporalField field,long newValue) performs
     case ALIGNED_DAY_OF_WEEK_IN_MONTH:
          return plusDays(newValue - getLong(ALIGNED_DAY_OF_WEEK_IN_MONTH));

The Symmetry010 is still incorrect with regards to

- ALIGNED_DAY_OF_WEEK_IN_MONTH
- ALIGNED_DAY_OF_WEEK_IN_YEAR
- ALIGNED_WEEK_OF_MONTH
- ALIGNED_WEEK_OF_YEAR

It is best to let the super-class sort out the correct behaviour in these cases.
I do not see a benefit in duplicating the behaviour locally to Symmetry010#with(TemporalField, long).

Do you agree on this ?

**Comment by Clockwork-Muse** [comment]
Yeah, probably best to let the super handle it.

**Comment by jodastephen** [comment]
Was this fixed by the recent PR?

**Comment by Clockwork-Muse** [comment]
...no, it was only partially fixed by #62.  Some of the getters and stuff still return incorrect values.

**Comment by catull** [comment]
I believe it is fixed now with the PR #64.

**Comment by jodastephen** [comment]
Thanks
