### ISSUE TITLE
Interval#parse(String) not working with time zones

### ISSUE THREAD

**Issue by nsommer** [ThreeTen/threeten-extra#66]
Calling `Interval#parse(String)` with an ISO-8601 interval consisting of start and end, both specifying a timezone, a `DateTimeParseException` gets thrown. Example string:

```
2016-06-15T15:44:57+02:00/2016-06-29T16:08:41+02:00
```

[joda-time](http://www.joda.org/joda-time/apidocs/org/joda/time/Interval.html)'s Interval implementation parses this string correctly. Is this behavior intended?

**Comment by jodastephen** [comment]
As implemented, the `Interval` parser only supports "Z" , not other offsets like "+02:00". I can't see any reason why this could not be changed however.

**Comment by nsommer** [comment]
I had a look at the source coude of the `Interval` class. Looks like - for start/end intervals - it simply extracts start and end by splitting by the `/` delimiter and then uses `Instant.parse(String)` to get the start and end instants.

As the `Instant` class used by threeten-extra is part of `java.time` and therefore included in the JRE, I suspect getting a patch accepted there is lot harder than submitting a PR here ...

**Comment by jodastephen** [comment]
A PR here is easy. Change the code from `Instant.parse` to `OffsetDateTime.parse`, adjusting the Javadoc and tests. You'll need a call to `OffsetDateTime.toInstant()` as well.
