### ISSUE TITLE
Interval.overlap

### ISSUE THREAD

**Issue by shivateja** [ThreeTen/threeten-extra#69]
I think it'd be great to have a function to calculate the actual overlap between two Intervals. I've needed this wherever I used Interval. Would love to submit a patch if it can make to the library!

**Comment by jodastephen** [comment]
I think `intersection` is what you want - https://github.com/ThreeTen/threeten-extra/blob/master/src/main/java/org/threeten/extra/Interval.java#L341 - although that method is new and may not be released yet.

**Comment by Xaerxess** [comment]
Would you mind doing a new release? It's the second time I'd like to use this feature and I'd like to use 1.1 instead of custom 1.1-SNAPSHOT.
