### ISSUE TITLE
TemporalAmount classes for Hours, Minutes and Seconds

### ISSUE THREAD

**Issue by fino** [ThreeTen/threeten-extra#73]
Hello, 
Are there any reasons for not having Amount classes for Hours, Minutes and Seconds?

**Comment by jodastephen** [comment]
The `Hours` and `Minutes` classes exist but are not released: https://github.com/ThreeTen/threeten-extra/tree/master/src/main/java/org/threeten/extra - The `Seconds` class is the same as `Duration` so wasn't added.

**Comment by fino** [comment]
Sorry, I do not know how I could omit those classes in Javadoc.  :(
Seconds is not the same as Duration because of precision, e.g.: `parse("PT0.2s")` .

**Comment by jodastephen** [comment]
The question with `Seconds` is whether it is different enough from `Duration` to justify having another class. To me, the fact that you can use `Duration` for more, isn't enough of a reason to add a more limited class.

**Comment by catull** [comment]
In my view, Chronology and Date do not have to support a precision below a day.
In other words, the date for the moment in time (MiT) of 2017-03-22T**07**:34:29
is referring to the same date as the MiT of 2017-03-22T**19**:34:29.

The main functionality of dealing with Chronology and Date is to be able to calcluate and manipulate  days, weeks, months, years, decades etc: add/subtract, measure time distance, and validate a date.

**Comment by fino** [comment]
@jodastephen It is somehow strange to me that for other popular units, amount-of-time classes exist, but not for second. :) I will work on that.

**Comment by raupachz** [comment]
Personally I would not mind  a `Seconds` class. It adds a better semantic value to variables. 

A statement like `private Seconds elapsed` is in my opinion better than `private Duration elapsed`, if the sole purpose is keep an amount of seconds around.

**Comment by jodastephen** [comment]
More popular than I would have thought, so I added it.

**Comment by fino** [comment]
Thank you Stephen.
