### ISSUE TITLE
Parsing support from P1D to Hours, Minutes and Seconds?

### ISSUE THREAD

**Issue by fino** [ThreeTen/threeten-extra#77]
There is probably an inconsistency between parsing from ISO8601 Period's day value to Hours, Minutes, Seconds and converting from `Period` objects.

Those methods throw error: `Text cannot be parsed to a ...`
```
Seconds.parse("P1D");
Minutes.parse("P1D");
Hours.parse("P1D");
```
Those methods work fine (for `Minutes` and `Hours` as well).
```
Duration.parse("P1D");
Seconds.from(Period.parse("P1D"));
Seconds.from(Days.of(1));
```
It is even possible to  `Seconds.from(Weeks.ONE)` but in this case `Duration.from(Weeks.ONE)` throws error.
I am unsure about this issue, please share your thoughts.

**Comment by jodastephen** [comment]
Yes, days should be supported for parsing
