### ISSUE TITLE
YearWeek.plusWeek(int)

### ISSUE THREAD

**Issue by jschneider** [ThreeTen/threeten-extra#79]
I try to get an YearWeek object representing the *next* week from now.
And I could not find a simple and convenient way.

I would have expected something like that:
YearWeek.now().plusWeeks(1)

**Comment by jschneider** [comment]
If you think this method could be helpful, I'd be glad to create a pull request

**Comment by Clockwork-Muse** [comment]
`plusWeeks` is in PR #78 , just waiting for it to get pulled in.
