### ISSUE TITLE
Interval constructors don't support Instant.MIN or Instant.MAX

### ISSUE THREAD

**Issue by ereboschi** [ThreeTen/threeten-extra#80]
I was curious about using unbounded Intervals. According to the source code, an Instant is "unbounded" if:
- `start.equals(Instant.MIN)`
- `end.equals(Instant.MAX)`

However, `Interval.parse()` chokes if passed either Instant.MIN or Instant.MAX:
`Interval.parse( "-1000000000-01-01T00:00:00Z/2008-05-11T15:30:00Z" )`
> java.time.format.DateTimeParseException: Text '-1000000000-01-01T00:00:00Z' could not be parsed: Invalid value for Year (valid values -999999999 - 999999999): -1000000000

`Interval.parse( "2007-03-01T13:00:00Z/+1000000000-12-31T23:59:59.999999999Z" )`
> java.time.format.DateTimeParseException: Text '+1000000000-12-31T23:59:59.999999999Z' could not be parsed: Invalid value for Year (valid values -999999999 - 999999999): 1000000000

I can create an unbounded Interval if I try something sneaky like:
```
Interval interval = Interval.ALL.withStart( Instant.parse( "2007-03-01T13:00:00Z" ) );
```
... but `Interval.parse()` still fails to deserialize Instant.MIN or Instant.MAX:
`Interval.parse( interval.toString() );`
> Exception in thread "main" java.time.format.DateTimeParseException: Text '+1000000000-12-31T23:59:59.999999999Z' could not be parsed: Invalid value for Year (valid values -999999999 - 999999999): 1000000000

Is there a way to support parsing MIN & MAX? I need to serialize/deserialize unbounded Intervals.

**Comment by catull** [comment]
This is IMHO a bug in Java 8.

Instant.MIN is defined as the moment in time at `-1000000000-01-01T00:00Z` (MIN_1).
Instant.MAX is defined as the moment in time at `+1000000000-12-31T23:59:59.999999999Z` (MAX_1), just before January 1st of the year 100000000**1**.

The validation of Instant - as far as years is concerned - relies on the enumeration `ChronoField` `YEAR`, which ranges from `-999_999_999` to `+999_999_999`.

This means that Instant above is actually only valid from `-999999-12-31T23:59.999999999Z` (MIN_2) to `+999999999-12-31T23:59:59.999999999Z` (MAX_2).

There are two ways to fix it.

Either Instant.MIX / Instant.MAX are recalculated to MIN_2 / MAX_2, or
`ChronoField` `YEAR` ranges from MIN_1 to MAX_1.

I am in favour of option 2.

Since this is not going to be fixed so soon, here is an alternative.

Use OffsetDateTime instances for starters, as documented [here].(http://www.threeten.org/threeten-extra/apidocs/org/threeten/extra/Interval.html#parse-java.lang.CharSequence-)
Use slightly reduced OffsetDateTime.MIN / OffsetDateTime.MAX as margins of the "unbounded" cases, like this here:

```java
package com.example;

import org.threeten.extra.Interval;

import java.time.Instant;
import java.time.OffsetDateTime;

public class Yesy {
    private static final Instant MIN_OFFSET_DATE_TIME = OffsetDateTime.MIN.plusDays (1L).toInstant ();
    private static final Instant MAX_OFFSET_DATE_TIME = OffsetDateTime.MAX.minusDays (1L).toInstant ();

    public static void main (String args[]) {
        System.out.println (Interval.parse (MIN_OFFSET_DATE_TIME.toString () + "/2008-05-11T15:30:00Z"));
        System.out.println (Interval.parse ("2008-05-11T15:30:00Z/" + MAX_OFFSET_DATE_TIME.toString ()));
    }
}
```

Good luck.

**Comment by catull** [comment]
The link above has a typo

> The string must consist of one of the following three formats:

but it lists 4 formats.

Preparing a PR as we speak.

**Comment by ereboschi** [comment]
Apologies for the delay, @catull. Thank you for your response. I agree that the exception above is thrown by Java's libraries, not ThreeTen's.

Furthermore, ISO-8601 leaves gaping holes in its Interval format that neither Java, ThreeTen, Time4J can address by themselves. e.g.:
- 8601 doesn't define how to represent an unbounded interval
- 8601 doesn't define how years 0000-1582 should be interpreted
- 8601 doesn't define how years before 0000 or after 9999 should be handled (or how many digits may be used)
- 8601 doesn't limit the number of digits to the right of the decimal in seconds, but doesn't define the behavior either
- 8601 allows omission of the 'T' in times, but it's not standard
- 8601 doesn't define how many leading zeros can be used
- etc. etc.

This probably isn't anything new to most familiar with 8601, but I just became acquainted with some of the finer points recently.

**Comment by MenoData** [comment]
@ereboschi About ISO-8601-compatibility of existing libraries here my answer:

- _8601 doesn't define how to represent an unbounded interval_
Correct. ISO-8601 is silent about this topic. Maybe not in the newest version (but I have still not bought the new draft - see https://www.iso.org/news/2017/02/Ref2164.html ) So all implementations and realizations of unbounded intervals are library extensions. For Time4J, I can state that it is at least possible to express/format an unbounded interval in different styles, see the class [InfinityStyle](http://time4j.net/javadoc-en/net/time4j/range/InfinityStyle.html).

- _8601 doesn't define how years 0000-1582 should be interpreted_
Not correct. The paper of 2006 says in words (section 3.2.1):
 
> For the purposes of this International Standard the calendar based on these rules is referred to as the Gregorian calendar. The use of this calendar for dates preceding the introduction of the Gregorian calendar (also called the proleptic Gregorian calendar) should only be by agreement of the partners in information interchange.

- _8601 doesn't define how years before 0000 or after 9999 should be handled (or how many digits may be used)_
Not correct. Section 3.5 says in words:

> By mutual agreement of the partners in information interchange, it is permitted to expand the component identifying the calendar year, which is otherwise limited to four digits. This enables reference to dates and times in calendar years outside the range supported by complete representations, i.e. before the start of the year [0000] or after the end of the year [9999]. 

- _8601 doesn't limit the number of digits to the right of the decimal in seconds, but doesn't define the behavior either_
Yes, the number of digits to the right of the decimal point is not limited. Of course, time libraries will always have a limited count of supported decimal digits. The existing libraries you mentioned support nanosecond resolution, so 9 digits are supported for decimal seconds. Higher resolutions can simply not be represented in the state of classes like `Instant`, 'Moment' etc.

- _8601 allows omission of the 'T' in times, but it's not standard_
The omission of the 'T'-separator is possible in customized formats. You are free to set up your own format pattern for classes like `java.time.format.DateTimeFormatter`, `ChronoFormatter` etc. The Time4J-class `Iso8601Format` also allows an **optional** leading 'T' for its time-only representations in parsing.

- _8601 doesn't define how many leading zeros can be used_
Correct. Here again: You are free to set up your own format pattern. And defining leading zeros is easily possible with Java-8 or Time4J, just look at the API of the formatter.Builder.

If you miss some features then I suggest you to file a concrete issue on what so ever library issue tracker. For JSR-310, I think Oracle is the right address.
