### ISSUE TITLE
An adjustable clock

### ISSUE THREAD

**Issue by michaelhixson** [ThreeTen/threeten-extra#83]
I think an adjustable `java.time.Clock` &mdash; one that lets users change which `Instant` is reported by `clock.instant()` at will &mdash; would be a useful addition to threeten-extra.

## Use case

**Short version:** I'd use it for testing.

**Long version:**

I've started following the best practices described in `Clock`'s javadocs, avoiding methods like `System.currentTimeMillis()` and `Instant.now()` in favor of asking a `Clock` instance for the current time.  The clock is managed with dependency injection.

In production I use `Clock.system(...)`.  In tests, none of the JDK-provided clocks give me quite what I want so I've had to implement my own.

When testing some clock-sensitive behavior of my application, I want to:

1. Set up the relevant components.
2. Do some clock-sensitive operation with the components.
3. Adjust the clock to simulate the passage of time.
4. Do another clock-sensitive operation and verify the result.

For example:

1. Set up the subscription engine.
2. Start a new monthly subscription.
3. Fast forward one month.
4. Verify that payment is due for the new subscription.

These components accept the clock as a constructor parameter (in step 1) and store it in a private final field.  When adjusting the clock (in step 3), I really want that to be a simple one-liner in my test code.

I think the best way to approach that problem is with a new kind of `java.time.Clock`, which is the subject of this feature request.

These alternatives seem undesirable:

* Recreate all of my components so that I can provide a new clock.
* Make the clock fields of my components non-final so that I can assign them a new clock.
* Avoid injecting or storing a clock directly in any of my components, use something like a `Supplier<Clock>` instead, and have the components call `clockSupplier.get()` (by whatever name) whenever they need the clock.
* Use a mocking library in tests to create a fake clock, and mock each method of the fake clock that the components happen to use.

## Requirements

* **Essential:** Construct a new clock with a given instant and zone.
* **Essential:** Replace the instant of an existing clock with a new instant.
* **Nice to have:** Atomically update the instant of an existing clock given its current instant.
* **Nice to have:** Speak in terms of local date-times instead of absolute instants.

## Proposed API

```java
import java.io.Serializable;
import java.time.Clock;
import java.time.Instant;
import java.time.LocalDateTime;
import java.time.ZoneId;
import java.util.function.UnaryOperator;

public final class AdjustableClock extends Clock implements Serializable {

  public static AdjustableClock atInstant(Instant instant, ZoneId zone);
  public static AdjustableClock atDateTime(LocalDateTime dateTime, ZoneId zone);

  public void setInstant(Instant instant);
  public void setDateTime(LocalDateTime dateTime);
  public void adjustInstant(UnaryOperator<Instant> adjustmentFunction);
  public void adjustDateTime(UnaryOperator<LocalDateTime> adjustmentFunction);

  @Override public AdjustableClock withZone(ZoneId zone);
  @Override public ZoneId getZone();
  @Override public Instant instant();
  @Override public boolean equals(Object obj);
  @Override public int hashCode();
  @Override public String toString();

}
```

---

Your thoughts?

**Comment by jodastephen** [comment]
Concept is fine. API tweaked slightly:

```java
public final class MutableClock extends Clock implements Serializable {

  public static MutableClock of(Instant instant, ZoneId zone);
  public static MutableClock of(LocalDateTime dateTime, ZoneId zone);

  public void setZone(DateTimeZone zone);
  public void setInstant(Instant instant);
  public void setDateTime(LocalDateTime dateTime);
  public void adjust(TemporalAdjuster adjuster);
  public void adjustInstant(UnaryOperator<Instant> adjustmentFunction);
  public void adjustDateTime(UnaryOperator<LocalDateTime> adjustmentFunction);

  @Override public MutableClock withZone(ZoneId zone);
  @Override public ZoneId getZone();
  @Override public Instant instant();
  @Override public boolean equals(Object obj);
  @Override public int hashCode();
  @Override public String toString();

}
```

**Comment by michaelhixson** [comment]
Thanks for the feedback.  The addition of `setZone` and `adjust(TemporalAdjuster)` makes me think:

* This class would store its state as `AtomicReference<ZonedDateTime>`.
* `adjust(TemporalAdjuster)` would operate on that `ZonedDateTime`.
* There should also be an `add(TemporalAmount)` method, which would operate on that `ZonedDateTime`.
* There is no longer a need for the `adjustInstant` and `adjustDateTime` methods; one that accepts `UnaryOperator<ZonedDateTime>` would be superior, though I wish I could think of a name that didn't clash with the "adjust" of "TemporalAdjuster".

Does that sound good to you?

I'd be happy to create a pull request for this.  Should I?

**Comment by jodastephen** [comment]
Given the API of `Clock` exposes `Instant` and `ZoneId`, it seems like those should be the two fields stored in `MutableClock` rather than `ZonedDateTime`. Keeping them separate would also be more performant for querying. However I can see the benefits of synchronizing on just `ZonedDateTime`.

Given the state-space, these methods are the minimum:

    public void setZone(DateTimeZone zone);
    public void setInstant(Instant instant);

Any additional methods are at a secondary level, ie. for convenience.

    public void add(TemporalAmount amount);
    public void setDateTime(ZonedDateTime dateTime);
    public void adjust(TemporalAdjuster adjuster);
    public void adjustDateTime(UnaryOperator<ZonedDateTime> adjustmentFunction);

The last one is helpful, as it can better be implemented by a lambda than the `TemporalAdjuster` one. In fact, if any method were to be dropped, it could be the `TemporalAdjuster` one.

I'm happy to see a PR in the style of the project, thanks.

**Comment by michaelhixson** [comment]
Almost there...  I'd like to get your thoughts on one issue.

If the instant and time-zone can both change, there's no way to do atomic reads.  Not through the  `Clock` interface.  One can read the `instant()` then  `getZone()`, but that might produce an instant & time-zone pairing that never existed together at once in the clock itself.  Most `now(clock)` factory methods for date-time types will call these two methods in succession, so they potentially suffer from this issue.

I'd like to be able to say the clock is "thread-safe" with as few qualifiers as possible, but I don't think I'd say "thread-safe" at all when describing this clock, if it has this issue.

We could say that it's safe as long as you don't change the time-zone while anyone else is reading the clock, but...

Why change the time zone anyway?  The application will expect a clock's instant to change, but it probably won't expect the time-zone to change, since other clocks disallow it.  I don't know what the purpose of such a test would be, to give the clock to a component *then* change the time-zone, where selecting a fixed time-zone up front wouldn't suffice.

My suggestion is to make the time-zone fixed, but I'll proceed with the PR either way.

Would you entertain a PR that makes the time-zone fixed, or would you prefer that I keep it mutable?

**Comment by jodastephen** [comment]
I'm happy to see the zone fixed. Users can still call `withZone()` to get a new instance with a different zone.
