### ISSUE TITLE
Interval around time/instant

### ISSUE THREAD

**Issue by andrewparmet** [ThreeTen/threeten-extra#85]
What I'm implementing for myself is a factory method for intervals of a certain duration symmetrically surrounding an instant; e.g., to check if something arrived within five minutes of noon on some day. Something like 
```java
Interval.surrounding(Instant center, Duration length)
```
that does the division by two, subtraction from the instant, and construction of the interval. Is there a clean way to do this, or does it make sense to add as a static factory in some form (perhaps with better names or without the division by two - e.g. specifying the half-length)?

Thanks for a great library!

**Comment by jodastephen** [comment]
Thanks for your suggestion.

There is no special way to do this beyond `Interval.of(instant.plus(duration), instant.minus(duration))`. But I think that is simple enough that it is not worth an extra method on the API. Sorry!
