### ISSUE TITLE
YearWeek.atDay() throws an exception if resulting LocalDate is in next year.

### ISSUE THREAD

**Issue by jezovuk** [ThreeTen/threeten-extra#86]
Example: `YearWeek.of(2016, 52).atDay(SUNDAY)`. It tries to create LocalDate with year 2016 and day-of-year 367 and explodes. Date-is-in-previous-year case seems to be supported.

**Comment by catull** [comment]
You are right.
`YearWeek.of(2016, 52).atDay(SUNDAY)` MUST evaluate to LocalDate of 2016-12-31.

The 52nd week of 2016 starts on St. Stephen's Day (2016-12-26).
The SUNDAY of that week falls on New Years Day (2017-01-01).
Each day in that period is contained in 2016-W52.

PR #87 corrects the bug you unearthed.

**Comment by jezovuk** [comment]
If I'm not mistaken, it should evaluate to LD 2017-01-01, not 2016-12-31.
